apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: notifications
  type: ClusterIP
status:
  loadBalancer: {}
